---
package_hardening_required_packages:
  - unattended-upgrades
package_hardening_optional_packages:
  - debsums
  - apt-show-versions
  - apt-listchanges
package_hardening_enable_unattended_upgrades: true
package_hardening_run_dist_upgrade: true
package_hardening_debsums_cron_check: "weekly"
package_hardening_purge_removed_packages: true
