---
kernel_sysctl_dropin_path: /etc/sysctl.d/99-zz-hardening.conf
kernel_sysctl_settings:
  dev.tty.ldisc_autoload: 0
  fs.suid_dumpable: 0
  fs.protected_fifos: 2
  kernel.randomize_va_space: 2
  kernel.core_uses_pid: 1
  kernel.kptr_restrict: 2
  kernel.dmesg_restrict: 1
  kernel.sysrq: 0
  kernel.unprivileged_bpf_disabled: 1
  kernel.yama.ptrace_scope: 1
  net.core.bpf_jit_harden: 2
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv6.conf.all.accept_redirects: 0
  net.ipv6.conf.default.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.accept_source_route: 0
  net.ipv6.conf.all.accept_source_route: 0
  net.ipv6.conf.default.accept_source_route: 0
  net.ipv4.icmp_echo_ignore_broadcasts: 1
  net.ipv4.icmp_ignore_bogus_error_responses: 1
  net.ipv4.tcp_syncookies: 1
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.log_martians: 1
  net.ipv4.conf.default.log_martians: 1
kernel_blacklisted_network_modules:
  - dccp
  - sctp
  - rds
  - tipc
kernel_disable_usb_storage: true
kernel_disable_firewire_storage: true
kernel_disable_core_dumps: true
kernel_lock_module_loading: false
